Tests are now being run by tox
Kinto/kinto-webextensions-tests pull request #3
Opened 2017-05-26 17:04 UTC by chartjes

2017-05-26 18:09 UTC, Natim commented on tox.ini
> +envlist = py3
envlist = py36,flake8

2017-05-26 18:10 UTC, Natim commented on tox.ini
> +deps = -rdev-requirements
why not just `flake8` there?

2017-05-26 18:10 UTC, Natim commented on tox.ini
> +skip_install = true
👍

2017-05-29 07:54 UTC, Natim requested changes

2017-05-29 07:54 UTC, Natim commented on tox.ini
> +whitelist_externals = flake8
We should install flake8 in the tox venv.

Something like: 
```
[testenv:flake8]
skip_install = true
deps = flake8
commands = flake8 {posargs: config-tests/}
```

2017-05-29 07:54 UTC, Natim commented on config-tests/test_webextensions_crud.py
> +        data,
nit: Maybe we can keep data on the previous line here?

2017-05-29 22:50 UTC, rpappalax commented on Dockerfile
>  RUN find . -name "*.pyc" | xargs rm -rf
it's probably better practice to put this cleanup in a .dockerignore (one less layer)

2017-05-30 16:14 UTC, rpappalax commented
+1 on my end

2017-12-06 14:51 UTC, closed without merging